const pmUser = {
  id: 10,
  username: 'mina.pm',
  email: 'mina.pm@example.com',
  is_superuser: false,
  is_staff: true,
  is_active: true,
  cn: 'MINA_PM',
  name: 'Mina Pham',
  display_name_printable: 'Mina Pham',
  title: 'Project Manager',
  department: 'Platform Engineering',
  desc: 'Owns sprint delivery and reporting.',
}

const plUser = {
  id: 20,
  username: 'hung.pl',
  email: 'hung.pl@example.com',
  is_superuser: false,
  is_staff: true,
  is_active: true,
  cn: 'HUNG_PL',
  name: 'Hung Le',
  display_name_printable: 'Hung Le',
  title: 'Project Lead',
  department: 'Core Services',
  desc: 'Owns technical execution and bug triage.',
}

const createSprintWindow = (
  year,
  month,
  startDay,
  endDay,
  endMonth = month,
) => ({
  start_date: `${year}-${String(month).padStart(2, '0')}-${String(startDay).padStart(2, '0')}`,
  end_date: `${year}-${String(endMonth).padStart(2, '0')}-${String(endDay).padStart(2, '0')}`,
})

const createMilestoneSprint = ({
  id,
  sprintId,
  sprintName,
  window,
  completedPoint,
  scopePoint,
  resolvedBug,
  totalBug,
  newBug,
  resolvedBugVelocity,
  targetBugVelocity = 0.9,
  targetReopenedRate = 0.03,
  resolvedBugReopened,
  reopenedBug,
  milestone,
  active = false,
}) => ({
  id,
  sprint: {
    id: sprintId,
    name: sprintName,
    start_date: window.start_date,
    end_date: window.end_date,
  },
  completed_point: completedPoint,
  scope_point: scopePoint,
  resolved_bug: resolvedBug,
  total_bug: totalBug,
  new_bug: newBug,
  resolved_bug_velocity: resolvedBugVelocity,
  target_bug_velocity: targetBugVelocity,
  target_reopened_rate: targetReopenedRate,
  resolved_bug_reopened: resolvedBugReopened,
  reopened_bug: reopenedBug,
  created_at: `${window.end_date}T18:09:29.282Z`,
  active,
  milestone,
})

export const projects = [
  {
    id: 101,
    pm: pmUser,
    pl: plUser,
    name: 'webOS TV Platform',
    key: 'WEBOS',
    description: 'Core platform maintenance and quality improvements.',
    members: 'Core Team, QA Team',
    labels: 'bugfix, sprint, platform',
  },
  {
    id: 102,
    pm: { ...pmUser, id: 11, username: 'tram.pm', name: 'Tram Nguyen' },
    pl: { ...plUser, id: 21, username: 'huy.pl', name: 'Huy Tran' },
    name: 'Streaming Reliability',
    key: 'STREAM',
    description: 'Playback reliability and performance backlog.',
    members: 'Media Team, QA Team',
    labels: 'reliability, defects',
  },
  {
    id: 103,
    pm: { ...pmUser, id: 12, username: 'linh.pm', name: 'Linh Do' },
    pl: { ...plUser, id: 22, username: 'quang.pl', name: 'Quang Bui' },
    name: 'Mobile Commerce Support Escalations',
    key: 'MCS',
    description:
      'Support-driven defect cleanup across payments, login, and order history.',
    members: 'Commerce Core, Mobile QA, Customer Care',
    labels: 'support, payments, mobile, escalation',
  },
  {
    id: 104,
    pm: { ...pmUser, id: 13, username: 'anh.pm', name: 'Anh Vu' },
    pl: { ...plUser, id: 23, username: 'kiet.pl', name: 'Kiet Hoang' },
    name: 'Internal Tooling Incubator',
    key: 'TOOLS',
    description: 'Early-stage reporting project without active milestones yet.',
    members: 'DX Team',
    labels: 'internal, reporting, incubator',
  },
]

export const milestonesByProject = {
  101: [
    {
      id: 1001,
      name: 'Sprint 10 Hardening',
      description: 'Stability and release hardening sprint.',
      start_date: '2026-03-02',
      end_date: '2026-03-13',
      closed_ticket: 64,
      total_ticket: 92,
      resolved_bug: 29,
      total_bug: 50,
      project: 101,
    },
    {
      id: 1002,
      name: 'Sprint 11 Recovery',
      description: 'Post-release bug closure sprint.',
      start_date: '2026-03-16',
      end_date: '2026-03-27',
      closed_ticket: 42,
      total_ticket: 80,
      resolved_bug: 18,
      total_bug: 32,
      project: 101,
    },
    {
      id: 1003,
      name: 'Regression Containment',
      description: 'Multi-squad focus on elevated bug intake after release.',
      start_date: '2026-03-30',
      end_date: '2026-04-24',
      closed_ticket: 71,
      total_ticket: 118,
      resolved_bug: 34,
      total_bug: 58,
      project: 101,
    },
  ],
  102: [
    {
      id: 2001,
      name: 'Playback Buffering Reduction',
      description: 'Focus on startup and buffering reliability.',
      start_date: '2026-03-02',
      end_date: '2026-03-13',
      closed_ticket: 55,
      total_ticket: 88,
      resolved_bug: 24,
      total_bug: 41,
      project: 102,
    },
    {
      id: 2002,
      name: 'CDN Edge Recovery',
      description:
        'Stabilize playback failures caused by regional cache misses.',
      start_date: '2026-03-16',
      end_date: '2026-04-03',
      closed_ticket: 39,
      total_ticket: 67,
      resolved_bug: 19,
      total_bug: 28,
      project: 102,
    },
  ],
  103: [
    {
      id: 3001,
      name: 'Payment Escalation Sweep',
      description:
        'Incoming support queue triage before formal sprint planning.',
      start_date: '2026-04-06',
      end_date: '2026-04-17',
      closed_ticket: 18,
      total_ticket: 33,
      resolved_bug: 7,
      total_bug: 14,
      project: 103,
    },
    {
      id: 3002,
      name: 'Session Reliability Hardening',
      description:
        'Follow-up milestone with active sprint data and sharper swings.',
      start_date: '2026-04-20',
      end_date: '2026-05-08',
      closed_ticket: 46,
      total_ticket: 74,
      resolved_bug: 21,
      total_bug: 27,
      project: 103,
    },
  ],
  104: [],
}

export const sprintsByMilestone = {
  1001: [
    createMilestoneSprint({
      id: 1,
      sprintId: 10001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 1, 1, 7),
      completedPoint: 4,
      scopePoint: 60,
      resolvedBug: 5,
      totalBug: 50,
      newBug: 9,
      resolvedBugVelocity: 7,
      resolvedBugReopened: 7,
      reopenedBug: 3,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 2,
      sprintId: 10002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 1, 8, 14),
      completedPoint: 11,
      scopePoint: 60,
      resolvedBug: 10,
      totalBug: 48,
      newBug: 9,
      resolvedBugVelocity: 8,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 3,
      sprintId: 10003,
      sprintName: 'Sprint 3',
      window: createSprintWindow(2026, 1, 15, 21),
      completedPoint: 17,
      scopePoint: 60,
      resolvedBug: 14,
      totalBug: 45,
      newBug: 12,
      resolvedBugVelocity: 11,
      resolvedBugReopened: 11,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 4,
      sprintId: 10004,
      sprintName: 'Sprint 4',
      window: createSprintWindow(2026, 1, 22, 28),
      completedPoint: 25,
      scopePoint: 60,
      resolvedBug: 19,
      totalBug: 42,
      newBug: 10,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 9,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 5,
      sprintId: 10005,
      sprintName: 'Sprint 5',
      window: createSprintWindow(2026, 1, 29, 31),
      completedPoint: 31,
      scopePoint: 60,
      resolvedBug: 23,
      totalBug: 38,
      newBug: 11,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 9,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 6,
      sprintId: 10006,
      sprintName: 'Sprint 6',
      window: createSprintWindow(2026, 2, 5, 11),
      completedPoint: 36,
      scopePoint: 80,
      resolvedBug: 24,
      totalBug: 40,
      newBug: 14,
      resolvedBugVelocity: 12,
      resolvedBugReopened: 11,
      reopenedBug: 3,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 7,
      sprintId: 10007,
      sprintName: 'Sprint 7',
      window: createSprintWindow(2026, 2, 12, 18),
      completedPoint: 42,
      scopePoint: 80,
      resolvedBug: 26,
      totalBug: 37,
      newBug: 14,
      resolvedBugVelocity: 13,
      resolvedBugReopened: 12,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 8,
      sprintId: 10008,
      sprintName: 'Sprint 8',
      window: createSprintWindow(2026, 2, 19, 25),
      completedPoint: 46,
      scopePoint: 80,
      resolvedBug: 27,
      totalBug: 34,
      newBug: 10,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 11,
      reopenedBug: 1,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 9,
      sprintId: 10009,
      sprintName: 'Sprint 9',
      window: createSprintWindow(2026, 2, 26, 28),
      completedPoint: 50,
      scopePoint: 80,
      resolvedBug: 28,
      totalBug: 33,
      newBug: 8,
      resolvedBugVelocity: 7,
      resolvedBugReopened: 7,
      reopenedBug: 1,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 10,
      sprintId: 10010,
      sprintName: 'Sprint 10',
      window: createSprintWindow(2026, 3, 5, 13),
      completedPoint: 53,
      scopePoint: 80,
      resolvedBug: 29,
      totalBug: 32,
      newBug: 6,
      resolvedBugVelocity: 6,
      resolvedBugReopened: 8,
      reopenedBug: 1,
      milestone: 1001,
      active: true,
    }),
  ],
  1002: [
    createMilestoneSprint({
      id: 11,
      sprintId: 11001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 16, 20),
      completedPoint: 8,
      scopePoint: 45,
      resolvedBug: 8,
      totalBug: 30,
      newBug: 10,
      resolvedBugVelocity: 8,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 1002,
    }),
    createMilestoneSprint({
      id: 12,
      sprintId: 11002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 3, 21, 27),
      completedPoint: 16,
      scopePoint: 50,
      resolvedBug: 18,
      totalBug: 26,
      newBug: 12,
      resolvedBugVelocity: 11,
      resolvedBugReopened: 10,
      reopenedBug: 1,
      milestone: 1002,
      active: true,
    }),
  ],
  1003: [
    createMilestoneSprint({
      id: 15,
      sprintId: 12001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 30, 3, 4),
      completedPoint: 10,
      scopePoint: 56,
      resolvedBug: 6,
      totalBug: 58,
      newBug: 14,
      resolvedBugVelocity: 8,
      targetBugVelocity: 1.1,
      targetReopenedRate: 0.025,
      resolvedBugReopened: 7,
      reopenedBug: 1,
      milestone: 1003,
    }),
    createMilestoneSprint({
      id: 16,
      sprintId: 12002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 4, 4, 10),
      completedPoint: 19,
      scopePoint: 62,
      resolvedBug: 11,
      totalBug: 55,
      newBug: 16,
      resolvedBugVelocity: 10,
      targetBugVelocity: 1.05,
      targetReopenedRate: 0.025,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 1003,
    }),
    createMilestoneSprint({
      id: 17,
      sprintId: 12003,
      sprintName: 'Sprint 3',
      window: createSprintWindow(2026, 4, 11, 17),
      completedPoint: 26,
      scopePoint: 70,
      resolvedBug: 18,
      totalBug: 52,
      newBug: 11,
      resolvedBugVelocity: 12,
      targetBugVelocity: 1,
      targetReopenedRate: 0.025,
      resolvedBugReopened: 10,
      reopenedBug: 1,
      milestone: 1003,
    }),
    createMilestoneSprint({
      id: 18,
      sprintId: 12004,
      sprintName: 'Sprint 4',
      window: createSprintWindow(2026, 4, 18, 24),
      completedPoint: 34,
      scopePoint: 70,
      resolvedBug: 27,
      totalBug: 48,
      newBug: 9,
      resolvedBugVelocity: 15,
      targetBugVelocity: 1,
      targetReopenedRate: 0.02,
      resolvedBugReopened: 14,
      reopenedBug: 0,
      milestone: 1003,
      active: true,
    }),
  ],
  2001: [
    createMilestoneSprint({
      id: 13,
      sprintId: 20001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 2, 6),
      completedPoint: 6,
      scopePoint: 48,
      resolvedBug: 9,
      totalBug: 32,
      newBug: 11,
      resolvedBugVelocity: 9,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 2001,
    }),
    createMilestoneSprint({
      id: 14,
      sprintId: 20002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 3, 7, 13),
      completedPoint: 15,
      scopePoint: 52,
      resolvedBug: 17,
      totalBug: 29,
      newBug: 14,
      resolvedBugVelocity: 13,
      resolvedBugReopened: 12,
      reopenedBug: 1,
      milestone: 2001,
      active: true,
    }),
  ],
  2002: [
    createMilestoneSprint({
      id: 19,
      sprintId: 21001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 16, 20),
      completedPoint: 7,
      scopePoint: 40,
      resolvedBug: 6,
      totalBug: 28,
      newBug: 8,
      resolvedBugVelocity: 7,
      targetBugVelocity: 0.95,
      targetReopenedRate: 0.035,
      resolvedBugReopened: 6,
      reopenedBug: 1,
      milestone: 2002,
    }),
    createMilestoneSprint({
      id: 20,
      sprintId: 21002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 3, 21, 27),
      completedPoint: 13,
      scopePoint: 44,
      resolvedBug: 10,
      totalBug: 27,
      newBug: 7,
      resolvedBugVelocity: 8,
      targetBugVelocity: 0.95,
      targetReopenedRate: 0.035,
      resolvedBugReopened: 7,
      reopenedBug: 1,
      milestone: 2002,
    }),
    createMilestoneSprint({
      id: 21,
      sprintId: 21003,
      sprintName: 'Sprint 3',
      window: createSprintWindow(2026, 3, 28, 3, 4),
      completedPoint: 24,
      scopePoint: 44,
      resolvedBug: 16,
      totalBug: 25,
      newBug: 6,
      resolvedBugVelocity: 11,
      targetBugVelocity: 0.95,
      targetReopenedRate: 0.03,
      resolvedBugReopened: 10,
      reopenedBug: 0,
      milestone: 2002,
    }),
  ],
  3001: [],
  3002: [
    createMilestoneSprint({
      id: 22,
      sprintId: 31001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 4, 20, 24),
      completedPoint: 5,
      scopePoint: 24,
      resolvedBug: 3,
      totalBug: 27,
      newBug: 9,
      resolvedBugVelocity: 4,
      targetBugVelocity: 0.85,
      targetReopenedRate: 0.04,
      resolvedBugReopened: 3,
      reopenedBug: 1,
      milestone: 3002,
    }),
    createMilestoneSprint({
      id: 23,
      sprintId: 31002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 4, 25, 30),
      completedPoint: 12,
      scopePoint: 30,
      resolvedBug: 8,
      totalBug: 23,
      newBug: 7,
      resolvedBugVelocity: 7,
      targetBugVelocity: 0.85,
      targetReopenedRate: 0.04,
      resolvedBugReopened: 6,
      reopenedBug: 1,
      milestone: 3002,
    }),
    createMilestoneSprint({
      id: 24,
      sprintId: 31003,
      sprintName: 'Sprint 3',
      window: createSprintWindow(2026, 5, 1, 8),
      completedPoint: 19,
      scopePoint: 30,
      resolvedBug: 14,
      totalBug: 21,
      newBug: 5,
      resolvedBugVelocity: 10,
      targetBugVelocity: 0.85,
      targetReopenedRate: 0.035,
      resolvedBugReopened: 9,
      reopenedBug: 0,
      milestone: 3002,
      active: true,
    }),
  ],
}

export const milestoneJqlById = {
  1001: 'project in (TVPLAT) AND labels in (fpt.flutter.factorywin) AND assignee in (manh.tranduc, hai.lehuu, tuan.ledinh, hoang.phamduc) AND startdate >= 2026-01-19 AND enddate <= 2026-03-13',
  1002: 'project in (TVPLAT) AND labels in (fpt.flutter.home) AND assignee in (phu.nguyenhoc, linh.nguyengia) AND startdate >= 2026-03-16 AND enddate <= 2026-03-27',
  1003: 'project in (TVPLAT, STREAM) AND labels in (regression, release-blocker) AND component in (player, launcher) AND startdate >= 2026-03-30 AND enddate <= 2026-04-24',
  2001: 'project in ("Q EVENT 26") AND labels in (fpt.flutter.home) AND assignee in (phu.nguyenhoc, linh.nguyengia) AND startdate >= 2026-01-19 AND enddate <= 2026-03-13',
  2002: 'project in (STREAM) AND labels in (cdn, playback) AND priority in (Highest, High) AND startdate >= 2026-03-16 AND enddate <= 2026-04-03',
  3001: 'project in (MCS) AND labels in (payments, escalation) AND created >= 2026-04-06 AND created <= 2026-04-17',
  3002: 'project in (MCS, TVPLAT) AND labels in (session, auth) AND assignee in (quang.bui, thao.tran) AND startdate >= 2026-04-20 AND enddate <= 2026-05-08',
}

const toCustomSummary = (milestoneId, sprints) => {
  const milestone = Object.values(milestonesByProject)
    .flat()
    .find((item) => item.id === milestoneId)

  return {
    start_date:
      milestone?.start_date ?? sprints[0]?.sprint.start_date ?? '2026-03-12',
    end_date:
      milestone?.end_date ??
      sprints[sprints.length - 1]?.sprint.end_date ??
      '2026-03-12',
    closed_ticket: milestone?.closed_ticket ?? 0,
    total_ticket: milestone?.total_ticket ?? 0,
    resolved_bug: milestone?.resolved_bug ?? 0,
    total_bug: milestone?.total_bug ?? 0,
  }
}

const toCustomSprints = (sprints) =>
  sprints.map(({ id, created_at, active, milestone: _, ...rest }) => rest)

const createCustomSummary = ({
  start_date,
  end_date,
  closed_ticket,
  total_ticket,
  resolved_bug,
  total_bug,
}) => ({
  start_date,
  end_date,
  closed_ticket,
  total_ticket,
  resolved_bug,
  total_bug,
})

export const customJqlResponses = [
  {
    match: /project\s+(?:=|in\s*\([^)]*MCS[^)]*\)).*payments/i,
    summary: toCustomSummary(3001, sprintsByMilestone[3001]),
    sprints: toCustomSprints(sprintsByMilestone[3001]),
  },
  {
    match: /project\s+(?:=|in\s*\([^)]*MCS[^)]*\)).*session/i,
    summary: toCustomSummary(3002, sprintsByMilestone[3002]),
    sprints: toCustomSprints(sprintsByMilestone[3002]),
  },
  {
    match: /project\s+(?:=|in\s*\([^)]*STREAM[^)]*\)).*cdn/i,
    summary: toCustomSummary(2002, sprintsByMilestone[2002]),
    sprints: toCustomSprints(sprintsByMilestone[2002]),
  },
  {
    match: /component\s+in\s*\(player,\s*launcher\)/i,
    summary: toCustomSummary(1003, sprintsByMilestone[1003]),
    sprints: toCustomSprints(sprintsByMilestone[1003]),
  },
  {
    match:
      /project\s+(?:=\s*(?:"Q EVENT 26"|Q\s+EVENT\s+26)|in\s*\([^)]*(?:"Q EVENT 26"|Q\s+EVENT\s+26)[^)]*\))/i,
    summary: toCustomSummary(2001, sprintsByMilestone[2001]),
    sprints: toCustomSprints(sprintsByMilestone[2001]),
  },
  {
    match: /labels\s+in\s*\(fpt\.flutter\.home\)/i,
    summary: toCustomSummary(1002, sprintsByMilestone[1002]),
    sprints: toCustomSprints(sprintsByMilestone[1002]),
  },
  {
    match: /project\s+(?:=\s*TVPLAT|in\s*\([^)]*TVPLAT[^)]*\))/i,
    summary: toCustomSummary(1001, sprintsByMilestone[1001]),
    sprints: toCustomSprints(sprintsByMilestone[1001]),
  },
  {
    match: /labels\s+in\s*\(unknown|empty\)/i,
    summary: createCustomSummary({
      start_date: '2026-04-01',
      end_date: '2026-04-01',
      closed_ticket: 5,
      total_ticket: 12,
      resolved_bug: 0,
      total_bug: 4,
    }),
    sprints: [],
  },
]
