const pmUser = {
  id: 10,
  username: 'mina.pm',
  email: 'mina.pm@example.com',
  is_superuser: false,
  is_staff: true,
  is_active: true,
  cn: 'MINA_PM',
  name: 'Mina Pham',
  display_name_printable: 'Mina Pham',
  title: 'Project Manager',
  department: 'Platform Engineering',
  desc: 'Owns sprint delivery and reporting.',
}

const plUser = {
  id: 20,
  username: 'hung.pl',
  email: 'hung.pl@example.com',
  is_superuser: false,
  is_staff: true,
  is_active: true,
  cn: 'HUNG_PL',
  name: 'Hung Le',
  display_name_printable: 'Hung Le',
  title: 'Project Lead',
  department: 'Core Services',
  desc: 'Owns technical execution and bug triage.',
}

const createSprintWindow = (year, month, startDay, endDay) => ({
  start_date: `${year}-${String(month).padStart(2, '0')}-${String(startDay).padStart(2, '0')}`,
  end_date: `${year}-${String(month).padStart(2, '0')}-${String(endDay).padStart(2, '0')}`,
})

const createMilestoneSprint = ({
  id,
  sprintId,
  sprintName,
  window,
  completedPoint,
  scopePoint,
  resolvedBug,
  totalBug,
  newBug,
  resolvedBugVelocity,
  resolvedBugReopened,
  reopenedBug,
  milestone,
  active = false,
}) => ({
  id,
  sprint: {
    id: sprintId,
    name: sprintName,
    start_date: window.start_date,
    end_date: window.end_date,
  },
  completed_point: completedPoint,
  scope_point: scopePoint,
  resolved_bug: resolvedBug,
  total_bug: totalBug,
  new_bug: newBug,
  resolved_bug_velocity: resolvedBugVelocity,
  target_bug_velocity: 0.9,
  target_reopened_rate: 0.03,
  resolved_bug_reopened: resolvedBugReopened,
  reopened_bug: reopenedBug,
  created_at: `${window.end_date}T18:09:29.282Z`,
  active,
  milestone,
})

export const projects = [
  {
    id: 101,
    pm: pmUser,
    pl: plUser,
    name: 'webOS TV Platform',
    key: 'WEBOS',
    description: 'Core platform maintenance and quality improvements.',
    members: 'Core Team, QA Team',
    labels: 'bugfix, sprint, platform',
  },
  {
    id: 102,
    pm: { ...pmUser, id: 11, username: 'tram.pm', name: 'Tram Nguyen' },
    pl: { ...plUser, id: 21, username: 'huy.pl', name: 'Huy Tran' },
    name: 'Streaming Reliability',
    key: 'STREAM',
    description: 'Playback reliability and performance backlog.',
    members: 'Media Team, QA Team',
    labels: 'reliability, defects',
  },
]

export const milestonesByProject = {
  101: [
    {
      id: 1001,
      name: 'Sprint 10 Hardening',
      description: 'Stability and release hardening sprint.',
      start_date: '2026-03-02',
      end_date: '2026-03-13',
      closed_ticket: 64,
      total_ticket: 92,
      resolved_bug: 29,
      total_bug: 50,
      project: 101,
    },
    {
      id: 1002,
      name: 'Sprint 11 Recovery',
      description: 'Post-release bug closure sprint.',
      start_date: '2026-03-16',
      end_date: '2026-03-27',
      closed_ticket: 42,
      total_ticket: 80,
      resolved_bug: 18,
      total_bug: 32,
      project: 101,
    },
  ],
  102: [
    {
      id: 2001,
      name: 'Playback Buffering Reduction',
      description: 'Focus on startup and buffering reliability.',
      start_date: '2026-03-02',
      end_date: '2026-03-13',
      closed_ticket: 55,
      total_ticket: 88,
      resolved_bug: 24,
      total_bug: 41,
      project: 102,
    },
  ],
}

export const sprintsByMilestone = {
  1001: [
    createMilestoneSprint({
      id: 1,
      sprintId: 10001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 1, 1, 7),
      completedPoint: 4,
      scopePoint: 60,
      resolvedBug: 5,
      totalBug: 50,
      newBug: 9,
      resolvedBugVelocity: 7,
      resolvedBugReopened: 7,
      reopenedBug: 3,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 2,
      sprintId: 10002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 1, 8, 14),
      completedPoint: 11,
      scopePoint: 60,
      resolvedBug: 10,
      totalBug: 48,
      newBug: 9,
      resolvedBugVelocity: 8,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 3,
      sprintId: 10003,
      sprintName: 'Sprint 3',
      window: createSprintWindow(2026, 1, 15, 21),
      completedPoint: 17,
      scopePoint: 60,
      resolvedBug: 14,
      totalBug: 45,
      newBug: 12,
      resolvedBugVelocity: 11,
      resolvedBugReopened: 11,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 4,
      sprintId: 10004,
      sprintName: 'Sprint 4',
      window: createSprintWindow(2026, 1, 22, 28),
      completedPoint: 25,
      scopePoint: 60,
      resolvedBug: 19,
      totalBug: 42,
      newBug: 10,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 9,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 5,
      sprintId: 10005,
      sprintName: 'Sprint 5',
      window: createSprintWindow(2026, 1, 29, 31),
      completedPoint: 31,
      scopePoint: 60,
      resolvedBug: 23,
      totalBug: 38,
      newBug: 11,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 9,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 6,
      sprintId: 10006,
      sprintName: 'Sprint 6',
      window: createSprintWindow(2026, 2, 5, 11),
      completedPoint: 36,
      scopePoint: 80,
      resolvedBug: 24,
      totalBug: 40,
      newBug: 14,
      resolvedBugVelocity: 12,
      resolvedBugReopened: 11,
      reopenedBug: 3,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 7,
      sprintId: 10007,
      sprintName: 'Sprint 7',
      window: createSprintWindow(2026, 2, 12, 18),
      completedPoint: 42,
      scopePoint: 80,
      resolvedBug: 26,
      totalBug: 37,
      newBug: 14,
      resolvedBugVelocity: 13,
      resolvedBugReopened: 12,
      reopenedBug: 2,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 8,
      sprintId: 10008,
      sprintName: 'Sprint 8',
      window: createSprintWindow(2026, 2, 19, 25),
      completedPoint: 46,
      scopePoint: 80,
      resolvedBug: 27,
      totalBug: 34,
      newBug: 10,
      resolvedBugVelocity: 10,
      resolvedBugReopened: 11,
      reopenedBug: 1,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 9,
      sprintId: 10009,
      sprintName: 'Sprint 9',
      window: createSprintWindow(2026, 2, 26, 28),
      completedPoint: 50,
      scopePoint: 80,
      resolvedBug: 28,
      totalBug: 33,
      newBug: 8,
      resolvedBugVelocity: 7,
      resolvedBugReopened: 7,
      reopenedBug: 1,
      milestone: 1001,
    }),
    createMilestoneSprint({
      id: 10,
      sprintId: 10010,
      sprintName: 'Sprint 10',
      window: createSprintWindow(2026, 3, 5, 13),
      completedPoint: 53,
      scopePoint: 80,
      resolvedBug: 29,
      totalBug: 32,
      newBug: 6,
      resolvedBugVelocity: 6,
      resolvedBugReopened: 8,
      reopenedBug: 1,
      milestone: 1001,
      active: true,
    }),
  ],
  1002: [
    createMilestoneSprint({
      id: 11,
      sprintId: 11001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 16, 20),
      completedPoint: 8,
      scopePoint: 45,
      resolvedBug: 8,
      totalBug: 30,
      newBug: 10,
      resolvedBugVelocity: 8,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 1002,
    }),
    createMilestoneSprint({
      id: 12,
      sprintId: 11002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 3, 21, 27),
      completedPoint: 16,
      scopePoint: 50,
      resolvedBug: 18,
      totalBug: 26,
      newBug: 12,
      resolvedBugVelocity: 11,
      resolvedBugReopened: 10,
      reopenedBug: 1,
      milestone: 1002,
      active: true,
    }),
  ],
  2001: [
    createMilestoneSprint({
      id: 13,
      sprintId: 20001,
      sprintName: 'Sprint 1',
      window: createSprintWindow(2026, 3, 2, 6),
      completedPoint: 6,
      scopePoint: 48,
      resolvedBug: 9,
      totalBug: 32,
      newBug: 11,
      resolvedBugVelocity: 9,
      resolvedBugReopened: 8,
      reopenedBug: 2,
      milestone: 2001,
    }),
    createMilestoneSprint({
      id: 14,
      sprintId: 20002,
      sprintName: 'Sprint 2',
      window: createSprintWindow(2026, 3, 7, 13),
      completedPoint: 15,
      scopePoint: 52,
      resolvedBug: 17,
      totalBug: 29,
      newBug: 14,
      resolvedBugVelocity: 13,
      resolvedBugReopened: 12,
      reopenedBug: 1,
      milestone: 2001,
      active: true,
    }),
  ],
}

export const milestoneJqlById = {
  1001: 'project = TVPLAT AND labels in (fpt.flutter.factorywin) AND assignee in (manh.tranduc, hai.lehuu, tuan.ledinh, hoang.phamduc) AND startdate >= 2026-01-19 AND enddate <= 2026-03-13',
  1002: 'project = TVPLAT AND labels in (fpt.flutter.home) AND assignee in (phu.nguyenhoc, linh.nguyengia) AND startdate >= 2026-03-16 AND enddate <= 2026-03-27',
  2001: 'project = "Q EVENT 26" AND labels in (fpt.flutter.home) AND assignee in (phu.nguyenhoc, linh.nguyengia) AND startdate >= 2026-01-19 AND enddate <= 2026-03-13',
}

const toCustomResponse = (milestoneId, sprints) => {
  const milestone = Object.values(milestonesByProject)
    .flat()
    .find((item) => item.id === milestoneId)

  return {
    start_date:
      milestone?.start_date ?? sprints[0]?.sprint.start_date ?? '2026-03-12',
    end_date:
      milestone?.end_date ??
      sprints[sprints.length - 1]?.sprint.end_date ??
      '2026-03-12',
    closed_ticket: milestone?.closed_ticket ?? 0,
    total_ticket: milestone?.total_ticket ?? 0,
    resolved_bug: milestone?.resolved_bug ?? 0,
    total_bug: milestone?.total_bug ?? 0,
    sprints: sprints.map(
      ({ id, created_at, active, milestone: _, ...rest }) => rest,
    ),
  }
}

export const customJqlResponses = [
  {
    match: /project\s*=\s*(?:"Q EVENT 26"|Q\s+EVENT\s+26)/i,
    response: toCustomResponse(2001, sprintsByMilestone[2001]),
  },
  {
    match: /labels\s+in\s*\(fpt\.flutter\.home\)/i,
    response: toCustomResponse(1002, sprintsByMilestone[1002]),
  },
  {
    match: /project\s*=\s*TVPLAT/i,
    response: toCustomResponse(1001, sprintsByMilestone[1001]),
  },
]
